(function () {
    const cfg = {
        id: 'newbie',
        name: '新人特惠寻访',
        description: '※寻访池内只有以下4级道具：柯吉猫的头、胎儿博士、圣饼、纵火狂、完美视力。<br/>※仅可抽取21次，次数用尽即结束。',
        hero: 'pools/newbie/hero.png',
        costSingle: 4,
        costTen: 36,
        pityStart: 50,
        pityIncrementPerDraw: 2,
        maxDraws: 21,
        guarantee3: true,
        guarantee4: true,
        items: [
            { id: '4', name: '柯吉猫的头', rank: 6, icon: '4.png' },
            { id: '52', name: '胎儿博士', rank: 6, icon: '52.png' },
            { id: '108', name: '圣饼', rank: 6, icon: '108.png' },
            { id: '223', name: '纵火狂', rank: 6, icon: '223.png' },
            { id: '245', name: '完美视力', rank: 6, icon: '245.png' },

            { id: '216', name: '仪式法袍', rank: 5, icon: '216.png' },
            { id: '127', name: '遗忘药', rank: 5, icon: '127.png' },
            { id: '58', name: '影之书', rank: 5, icon: '58.png' },
            { id: '170', name: '长腿蛛父', rank: 5, icon: '170.png' },
            { id: '306', name: '人马座', rank: 5, icon: '306.png' },
            { id: '184', name: '圣杯', rank: 5, icon: '184.png' },
            { id: '342', name: '蓝盖蘑菇', rank: 5, icon: '342.png' },
            { id: '98', name: '圣遗物', rank: 5, icon: '98.png' },
            { id: '196', name: '挤压玩具', rank: 5, icon: '196.png' },
            { id: '189', name: '超级食肉男孩死忠粉', rank: 5, icon: '189.png' },
            { id: '146', name: '祈祷卡', rank: 5, icon: '146.png' },
            { id: '203', name: '慈善捆绑包', rank: 5, icon: '203.png' },
            { id: '234', name: '害虫横行II', rank: 5, icon: '234.png' },
            { id: '260', name: '黑蜡烛', rank: 5, icon: '260.png' },
            { id: '249', name: '额外选择', rank: 5, icon: '249.png' },
            { id: '20', name: '超凡升天', rank: 5, icon: '20.png' },
            { id: '183', name: '牙签', rank: 5, icon: '183.png' },
            { id: '278', name: '黑暗乞丐', rank: 5, icon: '278.png' },
            { id: '341', name: '撕碎的照片', rank: 5, icon: '341.png' },
            { id: '79', name: '咒印', rank: 5, icon: '79.png' },
            { id: '104', name: '寄生虫', rank: 5, icon: '104.png' },
            { id: '261', name: '眼球突出', rank: 5, icon: '261.png' },
            { id: '132', name: '煤块', rank: 5, icon: '132.png' },
            { id: '48', name: '丘比特之箭', rank: 5, icon: '48.png' },
            { id: '3', name: '弯勺魔术', rank: 5, icon: '3.png' },
            { id: '7', name: '殉道者之血', rank: 5, icon: '7.png' },
            { id: '151', name: '虫群复击', rank: 5, icon: '151.png' },
            { id: '158', name: '水晶球', rank: 5, icon: '158.png' },
            { id: '80', name: '契约', rank: 5, icon: '80.png' },
            { id: '244', name: '科技0.5', rank: 5, icon: '244.png' },
            { id: '311', name: '犹大的影子', rank: 5, icon: '311.png' },
            { id: '199', name: '妈妈的钥匙', rank: 5, icon: '199.png' },
            { id: '307', name: '摩羯座', rank: 5, icon: '307.png' },
            { id: '150', name: '严厉的爱', rank: 5, icon: '150.png' },
            { id: '336', name: '烂洋葱', rank: 5, icon: '336.png' },

            { id: '213', name: '丢失的隐形眼镜', rank: 4, icon: '213.png' },
            { id: '92', name: '超级绷带', rank: 4, icon: '92.png' },
            { id: '296', name: '转换器', rank: 4, icon: '296.png' },
            { id: '85', name: '卡牌盒', rank: 4, icon: '85.png' },
            { id: '112', name: '守护天使', rank: 4, icon: '112.png' },
            { id: '120', name: '怪异蘑菇', rank: 4, icon: '120.png' },
            { id: '219', name: '旧绷带', rank: 4, icon: '219.png' },
            { id: '11', name: '1UP!', rank: 4, icon: '11.png' },
            { id: '248', name: '虫群之心', rank: 4, icon: '248.png' },
            { id: '34', name: '彼列之书', rank: 4, icon: '34.png' },
            { id: '206', name: '断头台', rank: 4, icon: '206.png' },
            { id: '228', name: '妈妈的香水', rank: 4, icon: '228.png' },
            { id: '253', name: '魔法血痂', rank: 4, icon: '253.png' },
            { id: '155', name: '窥眼', rank: 4, icon: '155.png' },
            { id: '222', name: '反重力', rank: 4, icon: '222.png' },
            { id: '257', name: '火焰意志', rank: 4, icon: '257.png' },
            { id: '64', name: 'Steam大促', rank: 4, icon: '64.png' },
            { id: '164', name: '蓝蜡烛', rank: 4, icon: '164.png' },
            { id: '309', name: '双鱼座', rank: 4, icon: '309.png' },
            { id: '145', name: '嗝屁猫的头', rank: 4, icon: '145.png' },
            { id: '324', name: '未定义', rank: 4, icon: '324.png' },
            { id: '101', name: '光环', rank: 4, icon: '101.png' },
            { id: '63', name: '蓄电池', rank: 4, icon: '63.png' },
            { id: '152', name: '科技II', rank: 4, icon: '152.png' },
            { id: '231', name: '焦油球', rank: 4, icon: '231.png' },
            { id: '229', name: '萌死戳的肺', rank: 4, icon: '229.png' },
            { id: '96', name: '查德宝宝', rank: 4, icon: '96.png' },
            { id: '14', name: '过量类固醇', rank: 4, icon: '14.png' },
            { id: '106', name: '大爆弹先生', rank: 4, icon: '106.png' },
            { id: '139', name: '妈妈的钱包', rank: 4, icon: '139.png' },
            { id: '100', name: '史蒂文宝宝', rank: 4, icon: '100.png' },
            { id: '166', name: '二十面骰', rank: 4, icon: '166.png' },
            { id: '205', name: '锋利插头', rank: 4, icon: '205.png' },
            { id: '175', name: '爸爸的钥匙', rank: 4, icon: '175.png' },
            { id: '38', name: '塔米猫的头', rank: 4, icon: '38.png' },

            { id: '24', name: '甜点', rank: 3, icon: '24.png' },
            { id: '93', name: '游戏掌机', rank: 3, icon: '93.png' },
            { id: '136', name: '最好的朋友', rank: 3, icon: '136.png' },
            { id: '174', name: '彩虹宝宝', rank: 3, icon: '174.png' },
            { id: '25', name: '早餐', rank: 3, icon: '25.png' },
            { id: '240', name: '实验性疗法', rank: 3, icon: '240.png' },
            { id: '86', name: '萌死戳的牙', rank: 3, icon: '86.png' },
            { id: '282', name: '跳跃教程', rank: 3, icon: '282.png' },
            { id: '66', name: '沙漏', rank: 3, icon: '66.png' },
            { id: '343', name: '弹簧锁钥匙', rank: 3, icon: '343.png' },
            { id: '204', name: '挎包', rank: 3, icon: '204.png' },
            { id: '33', name: '圣经', rank: 3, icon: '33.png' },
            { id: '35', name: '死灵之书', rank: 3, icon: '35.png' },
            { id: '55', name: '妈妈的眼睛', rank: 3, icon: '55.png' },
            { id: '47', name: '胎儿博士的遥控器', rank: 3, icon: '47.png' },
            { id: '272', name: '大美蝇', rank: 3, icon: '272.png' },
            { id: '323', name: '以撒的泪盆', rank: 3, icon: '323.png' },
            { id: '31', name: '妈妈的口红', rank: 3, icon: '31.png' },
            { id: '340', name: '咖啡因片', rank: 3, icon: '340.png' },
            { id: '60', name: '梯子', rank: 3, icon: '60.png' },
            { id: '137', name: '起爆器', rank: 3, icon: '137.png' },
            { id: '236', name: '大肠杆菌', rank: 3, icon: '236.png' },
            { id: '321', name: '参孙的脚镣', rank: 3, icon: '321.png' },
            { id: '161', name: '安卡十字', rank: 3, icon: '161.png' },
            { id: '167', name: '小丑宝宝', rank: 3, icon: '167.png' },
            { id: '320', name: '???唯一的朋友', rank: 3, icon: '320.png' },
            { id: '200', name: '妈妈的眼影', rank: 3, icon: '200.png' },
            { id: '26', name: '烂肉', rank: 3, icon: '26.png' },
            { id: '295', name: '魔术手指', rank: 3, icon: '295.png' },
            { id: '250', name: '炸弹买一送一', rank: 3, icon: '250.png' },
            { id: '210', name: '狸猫树叶', rank: 3, icon: '210.png' },
            { id: '171', name: '蜘蛛屁股', rank: 3, icon: '171.png' },
            { id: '102', name: '妈妈的药瓶', rank: 3, icon: '102.png' },
            { id: '338', name: '回旋镖', rank: 3, icon: '338.png' },
            { id: '140', name: '鲍勃的诅咒', rank: 3, icon: '140.png' },

            { id: '233', name: '小小星球', rank: 2, icon: '233.png' },
            { id: '211', name: '蜘蛛宝宝', rank: 2, icon: '211.png' },
            { id: '198', name: '盒子', rank: 2, icon: '198.png' },
            { id: '126', name: '剃刀片', rank: 2, icon: '126.png' },
            { id: '290', name: '罐子', rank: 2, icon: '290.png' },
            { id: '41', name: '妈妈的卫生巾', rank: 2, icon: '41.png' },
            { id: '186', name: '血之权利', rank: 2, icon: '186.png' },
            { id: '9', name: '粪臭素', rank: 2, icon: '9.png' },
            { id: '315', name: '怪异磁铁', rank: 2, icon: '315.png' },
            { id: '180', name: '黑豆', rank: 2, icon: '180.png' },
            { id: '117', name: '死鸟', rank: 2, icon: '117.png' },
            { id: '274', name: '生死之交', rank: 2, icon: '274.png' },
            { id: '74', name: '25美分', rank: 2, icon: '74.png' },
            { id: '59', name: '彼列之书', rank: 2, icon: '59.png' },
            { id: '40', name: '神风！', rank: 2, icon: '40.png' },
            { id: '19', name: '轰！', rank: 2, icon: '19.png' },
            { id: '56', name: '烦事柠檬', rank: 2, icon: '56.png' },
            { id: '276', name: '以撒的心脏', rank: 2, icon: '276.png' },
            { id: '177', name: '便携式老虎机', rank: 2, icon: '177.png' },
            { id: '316', name: '诅咒之眼', rank: 2, icon: '316.png' },
            { id: '148', name: '害虫横行', rank: 2, icon: '148.png' },
            { id: '44', name: '传送！', rank: 2, icon: '44.png' },
            { id: '111', name: '豆子', rank: 2, icon: '111.png' },
            { id: '188', name: '亚伯', rank: 2, icon: '188.png' },
            { id: '258', name: '编号丢失', rank: 2, icon: '258.png' },
            { id: '36', name: '大便', rank: 2, icon: '36.png' },
            { id: '252', name: '小药袋', rank: 2, icon: '252.png' },
            { id: '141', name: '盛装男孩', rank: 2, icon: '141.png' },

            { id: '-10', name: '随机血量', rank: 1, icon: '-10.png', weight: 0.25 },
            { id: '-30', name: '随机钥匙', rank: 1, icon: '-30.png', weight: 0.25 },
            { id: '-40', name: '随机炸弹', rank: 1, icon: '-40.png', weight: 0.25 },
            { id: '-50', name: '箱子', rank: 1, icon: '-50.png', weight: 0.03 },
            { id: '-51', name: '石头箱子', rank: 1, icon: '-51.png', weight: 0.01 },
            { id: '-52', name: '刺箱子', rank: 1, icon: '-52.png', weight: 0.01 },
            { id: '-60', name: '金箱子', rank: 1, icon: '-60.png', weight: 0.02 },
            { id: '-69', name: '福袋', rank: 1, icon: '-69.png', weight: 0.03 },
            { id: '-70', name: '随机胶囊', rank: 1, icon: '-70.png', weight: 0.03 },
            { id: '-90', name: '随机电池', rank: 1, icon: '-90.png', weight: 0.05 },
            { id: '-300', name: '随机卡牌', rank: 1, icon: '-300.png', weight: 0.03 },
            { id: '-350', name: '随机饰品', rank: 1, icon: '-350.png', weight: 0.03 },
            { id: '-360', name: '红箱子', rank: 1, icon: '-360.png'},
        ]
    };
    // 注册到 PoolManager
    window.PoolManager.register(cfg);
})();
