(function () {
    const cfg = {
        id: 'lilith',
        name: '特典·母性之光',
        description: '※寻访池内只有宝宝商店道具池道具及一般掉落物。<br/>※仅可抽取20次，次数用尽即结束。',
        hero: 'pools/lilith/hero.png',
        costSingle: 6,
        costTen: 54,
        pityStart: 50,
        pityIncrementPerDraw: 2,
        maxDraws: 20,
        guarantee3: true,
        items: [
            { id: '8', name: '波比兄弟', rank: 3, icon: 'icon/8.png' },
            { id: '10', name: '苍蝇光环', rank: 4, icon: 'icon/10.png' },
            { id: '57', name: '仰慕之交', rank: 4, icon: 'icon/57.png' },
            { id: '67', name: '玛姬姐妹', rank: 3, icon: 'icon/67.png' },
            { id: '73', name: '肉块', rank: 4, icon: 'icon/73.png' },
            { id: '88', name: '小胖蛆', rank: 4, icon: 'icon/88.png' },
            { id: '95', name: '机器宝宝', rank: 3, icon: 'icon/95.png' },
            { id: '96', name: '查德宝宝', rank: 4, icon: 'icon/96.png' },
            { id: '99', name: '吉什宝宝', rank: 4, icon: 'icon/99.png' },
            { id: '100', name: '史蒂文宝宝', rank: 4, icon: 'icon/100.png' },
            { id: '112', name: '守护天使', rank: 4, icon: 'icon/112.png' },
            { id: '113', name: '恶魔宝宝', rank: 4, icon: 'icon/113.png' },
            { id: '117', name: '死鸟', rank: 2, icon: 'icon/117.png' },
            { id: '128', name: '孤独一生', rank: 3, icon: 'icon/128.png' },
            { id: '144', name: '乞丐朋友', rank: 3, icon: 'icon/144.png' },
            { id: '155', name: '窥眼', rank: 4, icon: 'icon/155.png' },
            { id: '163', name: '幽灵宝宝', rank: 3, icon: 'icon/163.png' },
            { id: '167', name: '小丑宝宝', rank: 3, icon: 'icon/167.png' },
            { id: '170', name: '长腿蛛父', rank: 5, icon: 'icon/170.png' },
            { id: '172', name: '献祭匕首', rank: 4, icon: 'icon/172.png' },
            { id: '174', name: '彩虹宝宝', rank: 3, icon: 'icon/174.png' },
            { id: '188', name: '亚伯', rank: 2, icon: 'icon/188.png' },
            { id: '207', name: '绷带球', rank: 4, icon: 'icon/207.png' },
            { id: '264', name: '智能苍蝇', rank: 4, icon: 'icon/264.png' },
            { id: '265', name: '枯骨宝宝', rank: 5, icon: 'icon/265.png' },
            { id: '266', name: '粘液卵囊', rank: 4, icon: 'icon/266.png' },
            { id: '267', name: '机器宝宝2.0', rank: 3, icon: 'icon/267.png' },
            { id: '268', name: '腐烂宝宝', rank: 5, icon: 'icon/268.png' },
            { id: '269', name: '无头宝宝', rank: 3, icon: 'icon/269.png' },
            { id: '270', name: '水蛭', rank: 4, icon: 'icon/270.png' },
            { id: '272', name: '大美蝇', rank: 3, icon: 'icon/272.png' },
            { id: '273', name: '鲍勃的脑浆子', rank: 3, icon: 'icon/273.png' },
            { id: '274', name: '生死之交', rank: 2, icon: 'icon/274.png' },
            { id: '275', name: '硫磺火宝宝', rank: 4, icon: 'icon/275.png' },
            { id: '277', name: '恶灵宝宝', rank: 3, icon: 'icon/277.png' },
            { id: '278', name: '黑暗乞丐', rank: 5, icon: 'icon/278.png' },
            { id: '279', name: '大粉丝', rank: 4, icon: 'icon/279.png' },
            { id: '280', name: '长腿蛛妹妹', rank: 3, icon: 'icon/280.png' },
            { id: '281', name: '受气包', rank: 3, icon: 'icon/281.png' },
            { id: '320', name: '???唯一的朋友', rank: 3, icon: 'icon/320.png' },
            { id: '322', name: '蒙戈宝宝', rank: 4, icon: 'icon/322.png' },
            { id: '360', name: '淫魔', rank: 6, icon: 'icon/360.png' },
            { id: '361', name: '宿命的报答', rank: 4, icon: 'icon/361.png' },
            { id: '363', name: '宣誓守护者', rank: 5, icon: 'icon/363.png' },
            { id: '364', name: '浅交朋友', rank: 3, icon: 'icon/364.png' },
            { id: '365', name: '迷路苍蝇', rank: 4, icon: 'icon/365.png' },
            { id: '372', name: '充电宝宝', rank: 5, icon: 'icon/372.png' },
            { id: '384', name: '肉山宝宝', rank: 4, icon: 'icon/384.png' },
            { id: '385', name: '乞丐宝', rank: 3, icon: 'icon/385.png' },
            { id: '388', name: '钥匙乞丐', rank: 2, icon: 'icon/388.png' },
            { id: '390', name: '撒拉弗', rank: 5, icon: 'icon/390.png' },
            { id: '403', name: '蜘蛛模组', rank: 3, icon: 'icon/403.png' },
            { id: '404', name: '放屁宝宝', rank: 3, icon: 'icon/404.png' },
            { id: '417', name: '魅魔', rank: 5, icon: 'icon/417.png' },
            { id: '426', name: '狂热粉丝', rank: 2, icon: 'icon/426.png' },
            { id: '430', name: '狙击蝇老爹', rank: 3, icon: 'icon/430.png' },
            { id: '435', name: '洛基宝宝', rank: 3, icon: 'icon/435.png' },
            { id: '468', name: '阴影', rank: 2, icon: 'icon/468.png' },
            { id: '470', name: '死寂宝宝', rank: 2, icon: 'icon/470.png' },
            { id: '471', name: '萌死戳宝宝', rank: 4, icon: 'icon/471.png' },
            { id: '472', name: '国王宝宝', rank: 3, icon: 'icon/472.png' },
            { id: '473', name: '大胖蛆', rank: 3, icon: 'icon/473.png' },
            { id: '491', name: '毒瘾宝宝', rank: 4, icon: 'icon/491.png' },
            { id: '492', name: '嘿，听好！', rank: 4, icon: 'icon/492.png' },
            { id: '509', name: '血丝眼', rank: 3, icon: 'icon/509.png' },
            { id: '511', name: '愤怒苍蝇', rank: 3, icon: 'icon/511.png' },
            { id: '518', name: '伙伴盲盒', rank: 4, icon: 'icon/518.png' },
            { id: '519', name: '精神错乱宝宝', rank: 4, icon: 'icon/519.png' },
            { id: '537', name: '呕吐虫宝宝', rank: 3, icon: 'icon/537.png' },
            { id: '575', name: '侵体蜘蛛', rank: 5, icon: 'icon/575.png' },
            { id: '581', name: '灵能苍蝇', rank: 6, icon: 'icon/581.png' },
            { id: '607', name: '脓液囊宝宝', rank: 3, icon: 'icon/607.png' },
            { id: '608', name: '冰冻宝宝', rank: 4, icon: 'icon/608.png' },
            { id: '610', name: '鸟肥笼', rank: 3, icon: 'icon/610.png' },
            { id: '612', name: '迷失游魂', rank: 4, icon: 'icon/612.png' },
            { id: '615', name: '屁球宝宝', rank: 5, icon: 'icon/615.png' },
            { id: '629', name: '机器苍蝇', rank: 5, icon: 'icon/629.png' },
            { id: '635', name: '织布魔偶', rank: 3, icon: 'icon/635.png' },
            { id: '645', name: '小畸胎瘤', rank: 3, icon: 'icon/645.png' },
            { id: '649', name: '甜甜糖梅宝', rank: 3, icon: 'icon/649.png' },
            { id: '661', name: '五胞胎', rank: 4, icon: 'icon/661.png' },
            { id: '679', name: '亚巴顿宝宝', rank: 4, icon: 'icon/679.png' },
            { id: '682', name: '触手朋友', rank: 5, icon: 'icon/682.png' },
            { id: '698', name: '作孽双子', rank: 6, icon: 'icon/698.png' },

            { id: '-10', name: '随机血量', rank: 1, icon: '-10.png', weight: 0.25 },
            { id: '-30', name: '随机钥匙', rank: 1, icon: '-30.png', weight: 0.25 },
            { id: '-40', name: '随机炸弹', rank: 1, icon: '-40.png', weight: 0.25 },
            { id: '-50', name: '箱子', rank: 1, icon: '-50.png', weight: 0.03 },
            { id: '-51', name: '石头箱子', rank: 1, icon: '-51.png', weight: 0.01 },
            { id: '-52', name: '刺箱子', rank: 1, icon: '-52.png', weight: 0.01 },
            { id: '-60', name: '金箱子', rank: 1, icon: '-60.png', weight: 0.02 },
            { id: '-69', name: '福袋', rank: 1, icon: '-69.png', weight: 0.03 },
            { id: '-70', name: '随机胶囊', rank: 1, icon: '-70.png', weight: 0.03 },
            { id: '-90', name: '随机电池', rank: 1, icon: '-90.png', weight: 0.05 },
            { id: '-300', name: '随机卡牌', rank: 1, icon: '-300.png', weight: 0.03 },
            { id: '-350', name: '随机饰品', rank: 1, icon: '-350.png', weight: 0.03 },
            { id: '-360', name: '红箱子', rank: 1, icon: '-360.png' },
        ]
    };
    // 注册到 PoolManager
    window.PoolManager.register(cfg);
})();
